package dgroomes

import com.intellij.openapi.components.Service
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.ide.CopyPasteManager
import java.awt.datatransfer.StringSelection
import com.google.gson.Gson

/**
 * Fully generated by Sonnet 3.5. I don't fully endorse every line, but I've reviewed and approve the overall unit.
 */
@Service(Service.Level.PROJECT)
class CopyOpenTabsService(private val project: Project) {

    fun copyOpenTabNames(): List<String> {
        val fileEditorManager = FileEditorManager.getInstance(project)
        val openFiles = fileEditorManager.openFiles

        val fileNames = openFiles.map { it.name }

        val fileNamesString = fileNames.joinToString("\n")
        CopyPasteManager.getInstance().setContents(StringSelection(fileNamesString))

        return fileNames
    }

    fun getOpenTabsAsJson(): String {
        val fileEditorManager = FileEditorManager.getInstance(project)
        val openFiles = fileEditorManager.openFiles

        val fileInfoList = openFiles.map {
            mapOf(
                "name" to it.name,
                "path" to it.path,
                "extension" to it.extension
            )
        }

        val projectInfo = mapOf(
            "projectName" to project.name,
            "projectBasePath" to project.basePath,
            "openFiles" to fileInfoList
        )

        // The IntelliJ Platform uses Gson?? I don't understand which dependencies are available, and specifically which
        // are advertised to be available, which are "you technically can use them, but we can always remove them", and
        // which things are shaded and how the classloading works.
        return Gson().toJson(projectInfo)
    }
}
