[package]
name = "nushell-ast-printer"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-parser = "0.98.0"
nu-protocol = "0.98.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
