[package]
name = "nushell-ast-printer"
version = "0.1.0"
edition = "2021"

[dependencies]
new-nu-parser = { path = "../../../../opensource/new-nu-parser" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
