### Eclipse Temurin "Release Names"
#
# Find versions of Eclipse Temurin (the OpenJDK distribution from Adoptium). The Adoptium API is feature-rich and well-
# documented. You are encouraged to read the rendered Open API specification: https://api.adoptium.net/q/swagger-ui/
#
# I also like to browse the Adoptium website, and specifically the "Eclipse Temurin Latest Releases" page: https://adoptium.net/temurin/releases/
# You can even deep-link to the releases filtered down to a specific platform like Apple Silicon macOS: https://adoptium.net/temurin/releases/?os=mac&arch=aarch64&package=jdk
#
# The API has an upper limit of 20 results per page.
GET https://api.adoptium.net/v3/info/release_names?page=0&page_size=20&sort_order=DESC&sort_method=DATE

### Assets
#
# Get the assets for a given release. I'm confused about the various "assets/" endpoints. There are four of them! This
# one is working for me. The assets response describes the checksums of the installer/binary and the download links.
GET https://api.adoptium.net/v3/assets/release_name/eclipse/jdk-11.0.24+8?architecture=aarch64&image_type=jdk&os=mac&project=jdk

### Download Checksum
GET https://api.adoptium.net/v3/checksum/version/jdk-11.0.24+8/mac/aarch64/jdk/hotspot/normal/eclipse

### Download binary
GET https://api.adoptium.net/v3/binary/version/jdk-22.0.1+8/mac/aarch64/jdk/hotspot/normal/eclipse
