### Download Node.js Binaries
#
# Let's find Node.js binaries to download via HTTP.
#
# Reference:
#   - https://nodejs.org/en/download/prebuilt-binaries
#   - https://github.com/nodejs/node#verifying-binaries
#   - https://github.com/nodenv/node-build
GET https://nodejs.org/dist/v20.17.0/node-v20.17.0-darwin-arm64.tar.gz

### Checksum
GET https://nodejs.org/dist/v20.17.0/SHASUMS256.txt
