// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: java_body_omitter.proto
// Protobuf Java Version: 4.28.2

package dgroomes.java_body_omitter.proto;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error_message = 1 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 1 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
