// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: java_body_omitter.proto
// Protobuf Java Version: 4.28.2

package dgroomes.java_body_omitter.proto;

/**
 * Protobuf type {@code Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Response.class.getName());
  }
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Response() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dgroomes.java_body_omitter.proto.Response.class, dgroomes.java_body_omitter.proto.Response.Builder.class);
  }

  private int responseCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ERROR(1),
    SUCCESS(2),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return ERROR;
        case 2: return SUCCESS;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  /**
   * <code>.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return responseCase_ == 1;
  }
  /**
   * <code>.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public dgroomes.java_body_omitter.proto.Error getError() {
    if (responseCase_ == 1) {
       return (dgroomes.java_body_omitter.proto.Error) response_;
    }
    return dgroomes.java_body_omitter.proto.Error.getDefaultInstance();
  }
  /**
   * <code>.Error error = 1 [json_name = "error"];</code>
   */
  @java.lang.Override
  public dgroomes.java_body_omitter.proto.ErrorOrBuilder getErrorOrBuilder() {
    if (responseCase_ == 1) {
       return (dgroomes.java_body_omitter.proto.Error) response_;
    }
    return dgroomes.java_body_omitter.proto.Error.getDefaultInstance();
  }

  public static final int SUCCESS_FIELD_NUMBER = 2;
  /**
   * <code>.Success success = 2 [json_name = "success"];</code>
   * @return Whether the success field is set.
   */
  @java.lang.Override
  public boolean hasSuccess() {
    return responseCase_ == 2;
  }
  /**
   * <code>.Success success = 2 [json_name = "success"];</code>
   * @return The success.
   */
  @java.lang.Override
  public dgroomes.java_body_omitter.proto.Success getSuccess() {
    if (responseCase_ == 2) {
       return (dgroomes.java_body_omitter.proto.Success) response_;
    }
    return dgroomes.java_body_omitter.proto.Success.getDefaultInstance();
  }
  /**
   * <code>.Success success = 2 [json_name = "success"];</code>
   */
  @java.lang.Override
  public dgroomes.java_body_omitter.proto.SuccessOrBuilder getSuccessOrBuilder() {
    if (responseCase_ == 2) {
       return (dgroomes.java_body_omitter.proto.Success) response_;
    }
    return dgroomes.java_body_omitter.proto.Success.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (dgroomes.java_body_omitter.proto.Error) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (dgroomes.java_body_omitter.proto.Success) response_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (dgroomes.java_body_omitter.proto.Error) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (dgroomes.java_body_omitter.proto.Success) response_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dgroomes.java_body_omitter.proto.Response)) {
      return super.equals(obj);
    }
    dgroomes.java_body_omitter.proto.Response other = (dgroomes.java_body_omitter.proto.Response) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getError()
            .equals(other.getError())) return false;
        break;
      case 2:
        if (!getSuccess()
            .equals(other.getSuccess())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + getSuccess().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dgroomes.java_body_omitter.proto.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dgroomes.java_body_omitter.proto.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dgroomes.java_body_omitter.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dgroomes.java_body_omitter.proto.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Response)
      dgroomes.java_body_omitter.proto.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dgroomes.java_body_omitter.proto.Response.class, dgroomes.java_body_omitter.proto.Response.Builder.class);
    }

    // Construct using dgroomes.java_body_omitter.proto.Response.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (errorBuilder_ != null) {
        errorBuilder_.clear();
      }
      if (successBuilder_ != null) {
        successBuilder_.clear();
      }
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Response_descriptor;
    }

    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Response getDefaultInstanceForType() {
      return dgroomes.java_body_omitter.proto.Response.getDefaultInstance();
    }

    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Response build() {
      dgroomes.java_body_omitter.proto.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Response buildPartial() {
      dgroomes.java_body_omitter.proto.Response result = new dgroomes.java_body_omitter.proto.Response(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(dgroomes.java_body_omitter.proto.Response result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(dgroomes.java_body_omitter.proto.Response result) {
      result.responseCase_ = responseCase_;
      result.response_ = this.response_;
      if (responseCase_ == 1 &&
          errorBuilder_ != null) {
        result.response_ = errorBuilder_.build();
      }
      if (responseCase_ == 2 &&
          successBuilder_ != null) {
        result.response_ = successBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dgroomes.java_body_omitter.proto.Response) {
        return mergeFrom((dgroomes.java_body_omitter.proto.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dgroomes.java_body_omitter.proto.Response other) {
      if (other == dgroomes.java_body_omitter.proto.Response.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case ERROR: {
          mergeError(other.getError());
          break;
        }
        case SUCCESS: {
          mergeSuccess(other.getSuccess());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              responseCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getSuccessFieldBuilder().getBuilder(),
                  extensionRegistry);
              responseCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        dgroomes.java_body_omitter.proto.Error, dgroomes.java_body_omitter.proto.Error.Builder, dgroomes.java_body_omitter.proto.ErrorOrBuilder> errorBuilder_;
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     * @return Whether the error field is set.
     */
    @java.lang.Override
    public boolean hasError() {
      return responseCase_ == 1;
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     * @return The error.
     */
    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Error getError() {
      if (errorBuilder_ == null) {
        if (responseCase_ == 1) {
          return (dgroomes.java_body_omitter.proto.Error) response_;
        }
        return dgroomes.java_body_omitter.proto.Error.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return errorBuilder_.getMessage();
        }
        return dgroomes.java_body_omitter.proto.Error.getDefaultInstance();
      }
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     */
    public Builder setError(dgroomes.java_body_omitter.proto.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     */
    public Builder setError(
        dgroomes.java_body_omitter.proto.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     */
    public Builder mergeError(dgroomes.java_body_omitter.proto.Error value) {
      if (errorBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != dgroomes.java_body_omitter.proto.Error.getDefaultInstance()) {
          response_ = dgroomes.java_body_omitter.proto.Error.newBuilder((dgroomes.java_body_omitter.proto.Error) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          errorBuilder_.mergeFrom(value);
        } else {
          errorBuilder_.setMessage(value);
        }
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     */
    public dgroomes.java_body_omitter.proto.Error.Builder getErrorBuilder() {
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     */
    @java.lang.Override
    public dgroomes.java_body_omitter.proto.ErrorOrBuilder getErrorOrBuilder() {
      if ((responseCase_ == 1) && (errorBuilder_ != null)) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (dgroomes.java_body_omitter.proto.Error) response_;
        }
        return dgroomes.java_body_omitter.proto.Error.getDefaultInstance();
      }
    }
    /**
     * <code>.Error error = 1 [json_name = "error"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        dgroomes.java_body_omitter.proto.Error, dgroomes.java_body_omitter.proto.Error.Builder, dgroomes.java_body_omitter.proto.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = dgroomes.java_body_omitter.proto.Error.getDefaultInstance();
        }
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            dgroomes.java_body_omitter.proto.Error, dgroomes.java_body_omitter.proto.Error.Builder, dgroomes.java_body_omitter.proto.ErrorOrBuilder>(
                (dgroomes.java_body_omitter.proto.Error) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();
      return errorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        dgroomes.java_body_omitter.proto.Success, dgroomes.java_body_omitter.proto.Success.Builder, dgroomes.java_body_omitter.proto.SuccessOrBuilder> successBuilder_;
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     * @return Whether the success field is set.
     */
    @java.lang.Override
    public boolean hasSuccess() {
      return responseCase_ == 2;
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     * @return The success.
     */
    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Success getSuccess() {
      if (successBuilder_ == null) {
        if (responseCase_ == 2) {
          return (dgroomes.java_body_omitter.proto.Success) response_;
        }
        return dgroomes.java_body_omitter.proto.Success.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return successBuilder_.getMessage();
        }
        return dgroomes.java_body_omitter.proto.Success.getDefaultInstance();
      }
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     */
    public Builder setSuccess(dgroomes.java_body_omitter.proto.Success value) {
      if (successBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        successBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     */
    public Builder setSuccess(
        dgroomes.java_body_omitter.proto.Success.Builder builderForValue) {
      if (successBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        successBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     */
    public Builder mergeSuccess(dgroomes.java_body_omitter.proto.Success value) {
      if (successBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != dgroomes.java_body_omitter.proto.Success.getDefaultInstance()) {
          response_ = dgroomes.java_body_omitter.proto.Success.newBuilder((dgroomes.java_body_omitter.proto.Success) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          successBuilder_.mergeFrom(value);
        } else {
          successBuilder_.setMessage(value);
        }
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     */
    public Builder clearSuccess() {
      if (successBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        successBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     */
    public dgroomes.java_body_omitter.proto.Success.Builder getSuccessBuilder() {
      return getSuccessFieldBuilder().getBuilder();
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     */
    @java.lang.Override
    public dgroomes.java_body_omitter.proto.SuccessOrBuilder getSuccessOrBuilder() {
      if ((responseCase_ == 2) && (successBuilder_ != null)) {
        return successBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (dgroomes.java_body_omitter.proto.Success) response_;
        }
        return dgroomes.java_body_omitter.proto.Success.getDefaultInstance();
      }
    }
    /**
     * <code>.Success success = 2 [json_name = "success"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        dgroomes.java_body_omitter.proto.Success, dgroomes.java_body_omitter.proto.Success.Builder, dgroomes.java_body_omitter.proto.SuccessOrBuilder> 
        getSuccessFieldBuilder() {
      if (successBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = dgroomes.java_body_omitter.proto.Success.getDefaultInstance();
        }
        successBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            dgroomes.java_body_omitter.proto.Success, dgroomes.java_body_omitter.proto.Success.Builder, dgroomes.java_body_omitter.proto.SuccessOrBuilder>(
                (dgroomes.java_body_omitter.proto.Success) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();
      return successBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Response)
  }

  // @@protoc_insertion_point(class_scope:Response)
  private static final dgroomes.java_body_omitter.proto.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dgroomes.java_body_omitter.proto.Response();
  }

  public static dgroomes.java_body_omitter.proto.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dgroomes.java_body_omitter.proto.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

