// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: java_body_omitter.proto
// Protobuf Java Version: 4.28.2

package dgroomes.java_body_omitter.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Error error = 1 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.Error error = 1 [json_name = "error"];</code>
   * @return The error.
   */
  dgroomes.java_body_omitter.proto.Error getError();
  /**
   * <code>.Error error = 1 [json_name = "error"];</code>
   */
  dgroomes.java_body_omitter.proto.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.Success success = 2 [json_name = "success"];</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>.Success success = 2 [json_name = "success"];</code>
   * @return The success.
   */
  dgroomes.java_body_omitter.proto.Success getSuccess();
  /**
   * <code>.Success success = 2 [json_name = "success"];</code>
   */
  dgroomes.java_body_omitter.proto.SuccessOrBuilder getSuccessOrBuilder();

  dgroomes.java_body_omitter.proto.Response.ResponseCase getResponseCase();
}
