// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: java_body_omitter.proto
// Protobuf Java Version: 4.28.2

package dgroomes.java_body_omitter.proto;

/**
 * Protobuf type {@code Success}
 */
public final class Success extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Success)
    SuccessOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Success.class.getName());
  }
  // Use Success.newBuilder() to construct.
  private Success(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Success() {
    javaCode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Success_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Success_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dgroomes.java_body_omitter.proto.Success.class, dgroomes.java_body_omitter.proto.Success.Builder.class);
  }

  public static final int JAVA_CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object javaCode_ = "";
  /**
   * <code>string java_code = 1 [json_name = "javaCode"];</code>
   * @return The javaCode.
   */
  @java.lang.Override
  public java.lang.String getJavaCode() {
    java.lang.Object ref = javaCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      javaCode_ = s;
      return s;
    }
  }
  /**
   * <code>string java_code = 1 [json_name = "javaCode"];</code>
   * @return The bytes for javaCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJavaCodeBytes() {
    java.lang.Object ref = javaCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      javaCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(javaCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, javaCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(javaCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, javaCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dgroomes.java_body_omitter.proto.Success)) {
      return super.equals(obj);
    }
    dgroomes.java_body_omitter.proto.Success other = (dgroomes.java_body_omitter.proto.Success) obj;

    if (!getJavaCode()
        .equals(other.getJavaCode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JAVA_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getJavaCode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dgroomes.java_body_omitter.proto.Success parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dgroomes.java_body_omitter.proto.Success parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dgroomes.java_body_omitter.proto.Success parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dgroomes.java_body_omitter.proto.Success prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Success}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Success)
      dgroomes.java_body_omitter.proto.SuccessOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Success_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Success_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dgroomes.java_body_omitter.proto.Success.class, dgroomes.java_body_omitter.proto.Success.Builder.class);
    }

    // Construct using dgroomes.java_body_omitter.proto.Success.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      javaCode_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dgroomes.java_body_omitter.proto.JavaBodyOmitterProto.internal_static_Success_descriptor;
    }

    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Success getDefaultInstanceForType() {
      return dgroomes.java_body_omitter.proto.Success.getDefaultInstance();
    }

    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Success build() {
      dgroomes.java_body_omitter.proto.Success result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dgroomes.java_body_omitter.proto.Success buildPartial() {
      dgroomes.java_body_omitter.proto.Success result = new dgroomes.java_body_omitter.proto.Success(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dgroomes.java_body_omitter.proto.Success result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.javaCode_ = javaCode_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dgroomes.java_body_omitter.proto.Success) {
        return mergeFrom((dgroomes.java_body_omitter.proto.Success)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dgroomes.java_body_omitter.proto.Success other) {
      if (other == dgroomes.java_body_omitter.proto.Success.getDefaultInstance()) return this;
      if (!other.getJavaCode().isEmpty()) {
        javaCode_ = other.javaCode_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              javaCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object javaCode_ = "";
    /**
     * <code>string java_code = 1 [json_name = "javaCode"];</code>
     * @return The javaCode.
     */
    public java.lang.String getJavaCode() {
      java.lang.Object ref = javaCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        javaCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string java_code = 1 [json_name = "javaCode"];</code>
     * @return The bytes for javaCode.
     */
    public com.google.protobuf.ByteString
        getJavaCodeBytes() {
      java.lang.Object ref = javaCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string java_code = 1 [json_name = "javaCode"];</code>
     * @param value The javaCode to set.
     * @return This builder for chaining.
     */
    public Builder setJavaCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      javaCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string java_code = 1 [json_name = "javaCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJavaCode() {
      javaCode_ = getDefaultInstance().getJavaCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string java_code = 1 [json_name = "javaCode"];</code>
     * @param value The bytes for javaCode to set.
     * @return This builder for chaining.
     */
    public Builder setJavaCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      javaCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Success)
  }

  // @@protoc_insertion_point(class_scope:Success)
  private static final dgroomes.java_body_omitter.proto.Success DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dgroomes.java_body_omitter.proto.Success();
  }

  public static dgroomes.java_body_omitter.proto.Success getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Success>
      PARSER = new com.google.protobuf.AbstractParser<Success>() {
    @java.lang.Override
    public Success parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Success> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Success> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dgroomes.java_body_omitter.proto.Success getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

