// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: java_body_omitter.proto
// Protobuf Java Version: 4.28.2

package dgroomes.java_body_omitter.proto;

public interface SuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Success)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string java_code = 1 [json_name = "javaCode"];</code>
   * @return The javaCode.
   */
  java.lang.String getJavaCode();
  /**
   * <code>string java_code = 1 [json_name = "javaCode"];</code>
   * @return The bytes for javaCode.
   */
  com.google.protobuf.ByteString
      getJavaCodeBytes();
}
