[versions]
assertj = "3.26.3" # AssertJ releases: https://github.com/assertj/assertj-core/tags
intellij-platform-gradle-plugin = "2.0.1" # IntelliJ Platform Gradle Plugin releases: https://github.com/JetBrains/intellij-platform-gradle-plugin/releases
jackson = "2.17.2" # Jackson releases: https://github.com/FasterXML/jackson/wiki/Jackson-Releases
javaparser = "3.26.2" # JavaParser releases: https://github.com/javaparser/javaparser/releases
jetbrains-markdown = "0.7.3" # JetBrains Maven releases: https://central.sonatype.com/artifact/org.jetbrains/markdown?smo=true
junit-jupiter = "5.10.3" # JUnit releases: https://junit.org/junit5/docs/current/release-notes/index.html
mcp = "0.5.0" # Kotlin SDK for MCP releases: https://github.com/modelcontextprotocol/kotlin-sdk/releases

# Versioning of the Protobuf toolchain is unique. Study it here: https://protobuf.dev/support/version-support/
#
# Track releases in the GitHub Releases page: https://github.com/protocolbuffers/protobuf/releases
protobuf-java = "4.28.2"
slf4j = "2.0.16" # SLF4J releases: http://www.slf4j.org/news.html


[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
javaparser-core = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }
jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "jetbrains-markdown" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
mcp-kotlin-sdk = { module = "io.modelcontextprotocol:kotlin-sdk", version.ref = "mcp" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }


[plugins]
intellij-platform-gradle-plugin = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform-gradle-plugin" }

# Gradle's support for Kotlin: https://docs.gradle.org/current/userguide/compatibility.html
# Kotlin's support for Gradle https://kotlinlang.org/docs/gradle.html
kotlin-jvm = { version = "2.1.0", id = "org.jetbrains.kotlin.jvm" }
kotlin-serialization = { version = "2.1.0", id = "org.jetbrains.kotlin.plugin.serialization" }
